CREATE USER IF NOT EXISTS f1_app
IDENTIFIED WITH plaintext_password BY 'f1_app_password';

GRANT CREATE DATABASE ON *.* TO f1_app;

GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE ON raw.* TO f1_app;
GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE ON dwh.* TO f1_app;
GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE ON marts.* TO f1_app;
GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE ON monitoring.* TO f1_app;
GRANT SELECT ON system.* TO f1_app;
